#!/bin/sh
# Writes backend/supabase-install.sql: the whole database in one file, for pasting into a SQL editor.
#
# Installing normally is `psql -f` four times in order, and that needs a terminal. A managed database has
# a SQL editor in its own dashboard, and the four files contain no psql meta-commands and no \gexec — so
# pasting them as one is the same install with no terminal in it. Two things have to change on the way:
#
#   * **The four BEGIN/COMMIT pairs come out.** A dashboard SQL editor sends the whole buffer as one
#     statement and runs it inside a transaction it opened itself. The inner BEGINs then warn "there is
#     already a transaction in progress" and the first inner COMMIT ends the editor's transaction early —
#     so a failure in views.sql would leave the first three files committed, which is the one outcome
#     worth preventing: a database that looks installed. With them gone the editor's own transaction
#     covers all four files, and a failure anywhere undoes everything.
#   * **A self-check goes on the end.** Without a terminal there is no exit status to read, so the file
#     finishes by asking the database whether the install is actually there and raising an error in plain
#     words if it is not. It counts nothing that would go stale — it asks for one thing out of each of the
#     four files, and for the property that matters more than any count: no table left without row
#     security.
#
# Generated rather than written, and checked by backend/test-deploy.js against a fresh concatenation,
# because a second copy of 7,000 lines of schema is a second copy that drifts. Run this after changing
# any of the four.
set -e
HERE=$(dirname "$0")
OUT="$HERE/supabase-install.sql"

{
  echo "-- Varmak Workshop — the whole database, in one file, for a SQL editor."
  echo "--"
  echo "-- GENERATED by backend/make-supabase-install.sh from schema.sql, auth.sql, api.sql and views.sql."
  echo "-- Do not edit this file: edit those and run the script again. There is nothing in here to fill in."
  echo "--"
  echo "-- Paste the whole thing into the SQL editor and press Run, once. It makes the tables, the rules"
  echo "-- about who may read what, the workflows and the views, and then checks that it worked — if"
  echo "-- anything is missing you get an error saying which part, not a quiet half-install."
  echo "--"
  echo "-- It does NOT set the server's password and it does not create any person. Both are separate, on"
  echo "-- purpose: the password is backend/supabase-password.sql, the first administrator is /admin.html."
  echo "--"
  echo "-- It goes into an EMPTY database and refuses any other kind, in its first few lines and before it"
  echo "-- writes anything. Nothing in here is repeatable — none of the 39 tables or 18 counters is created"
  echo "-- with IF NOT EXISTS, because a table that already exists is a database somebody is already using"
  echo "-- and the last thing it needs is this file guessing. A second run is refused, in words."
  echo "--"
  echo "-- If a run fails partway it is undone completely: the editor runs the whole file in one"
  echo "-- transaction and this file takes care not to end it early. So a failure leaves the database as"
  echo "-- empty as it was, and pasting it again after fixing what the error said is the right thing to do."
  echo "--"
  echo "-- From a terminal, use backend/install.sh instead. This file has no transaction of its own —"
  echo "-- it relies on the editor's — so psql would commit it statement by statement."
  echo ""
  cat <<'PRECHECK'
-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- Is this database empty?
-- ═══════════════════════════════════════════════════════════════════════════════════════════
--
-- Added by backend/make-supabase-install.sh. Without it, a second run stops on "relation
-- seq_customer already exists" — true, unhelpful, and 48 lines into a 7,000-line file. Asked
-- first, so the answer arrives before anything is written and in a sentence that says what to do.

DO $precheck$
BEGIN
  -- invoice_basis is the last thing the last file makes; seq_customer is the first thing the first
  -- file makes. Between them they tell a finished install from one that stopped partway, and those
  -- two cases need opposite advice.
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
              WHERE n.nspname = 'public' AND p.proname = 'invoice_basis') THEN
    RAISE EXCEPTION E'Nothing was changed: Varmak Workshop is already installed in this database.\n\nIf this is the database you meant, you are finished with this file — next is backend/supabase-password.sql.\nIf you meant to start over, make a new empty database and paste this into that one. Running it here would not clear anything out, and this refuses rather than make a mess of a database somebody may already be working in.';
  END IF;
  IF to_regclass('public.seq_customer') IS NOT NULL THEN
    RAISE EXCEPTION E'Nothing was changed: this database holds part of Varmak Workshop — an install that stopped partway.\n\nThis file only installs into an empty database, so the result is never half of one. Make a new empty database and paste this into that one.';
  END IF;
END
$precheck$;
PRECHECK
  for f in schema auth api views; do
    echo ""
    echo "-- ═══════════════════════════════════════════════════════════════════════════════════════════"
    echo "-- $f.sql"
    echo "-- ═══════════════════════════════════════════════════════════════════════════════════════════"
    echo ""
    sed -e 's/^BEGIN;$/-- BEGIN; (removed: the SQL editor opens the transaction that covers all four files)/' \
        -e 's/^COMMIT;$/-- COMMIT; (removed: ending it here would commit a part of the install on its own)/' \
        "$HERE/$f.sql"
  done
  cat <<'SELFCHECK'

-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- Did it work?
-- ═══════════════════════════════════════════════════════════════════════════════════════════
--
-- Added by backend/make-supabase-install.sh, and in none of the four files: it exists because a SQL
-- editor has no exit status. One thing out of each file, and then the question no count can answer.

DO $selfcheck$
DECLARE
  missing text[] := '{}';
  unguarded text;
BEGIN
  -- The LAST thing each of the four files creates, so "did not finish" means what it says. Looked up by
  -- name rather than by signature, because a signature in here is a copy that goes stale quietly; and
  -- for two of them together with the grant that is genuinely the file's final line.
  IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
                  WHERE n.nspname = 'public' AND p.proname = 'issue_stock') THEN
    missing := missing || 'the tables (schema.sql did not finish)'::text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                  WHERE schemaname = 'public' AND policyname = 'the_office_runs_the_qualifications') THEN
    missing := missing || 'the rules about who may read what (auth.sql did not finish)'::text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
                  WHERE n.nspname = 'public' AND p.proname = 'book_hours'
                    AND has_function_privilege('varmak_workshop', p.oid, 'EXECUTE')) THEN
    missing := missing || 'the workflows (api.sql did not finish)'::text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
                  WHERE n.nspname = 'public' AND p.proname = 'invoice_basis'
                    AND has_function_privilege('varmak_office', p.oid, 'EXECUTE')) THEN
    missing := missing || 'what the screens read (views.sql did not finish)'::text;
  END IF;

  IF array_length(missing, 1) > 0 THEN
    RAISE EXCEPTION E'This install is not complete. Missing: %.\n\nNothing was written — the whole file is one transaction and it has just been undone, so the database is as empty as it was. Fix what the error above this one says and paste the file again.',
      array_to_string(missing, '; ');
  END IF;

  -- The count that would go stale is the number of tables. The one that cannot is this: a table with row
  -- security switched off is readable by anybody the server lets in, whatever the policies say.
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname) INTO unguarded
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r'
      AND NOT (c.relrowsecurity AND c.relforcerowsecurity);
  IF unguarded IS NOT NULL THEN
    RAISE EXCEPTION E'These tables came out without row security: %.\n\nThat would let anybody the server lets in read every row of them, whatever the rules say, so this refuses to finish. Nothing was written — paste the file again into an empty database.', unguarded;
  END IF;

  RAISE NOTICE 'Varmak Workshop is installed. Nobody can sign in yet — that is correct.';
  RAISE NOTICE 'Next: run backend/supabase-password.sql to give the server its password, then open /admin.html to make the first administrator.';
END
$selfcheck$;
SELFCHECK
} > "$OUT"

# The generator checks its own work: four BEGINs out, four COMMITs out, and none left behind. A sed that
# silently matched nothing would produce a file that installs in four pieces, which is the thing this is
# for preventing.
left=$(grep -c '^BEGIN;$' "$OUT" || true)
leftc=$(grep -c '^COMMIT;$' "$OUT" || true)
took=$(grep -c '^-- BEGIN; (removed' "$OUT" || true)
tookc=$(grep -c '^-- COMMIT; (removed' "$OUT" || true)
if [ "$left" != 0 ] || [ "$leftc" != 0 ] || [ "$took" != 4 ] || [ "$tookc" != 4 ]; then
  echo "Refusing to leave $OUT as it is: expected 4 BEGINs and 4 COMMITs taken out and none left," >&2
  echo "got $took and $tookc taken out, $left and $leftc left in." >&2
  exit 1
fi

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
